#!/bin/bash

if [ ! -z "${QUERY_STRING:-}" ]; then
  camera=$(echo "$QUERY_STRING" | sed 's/.*camera=\([^&]*\).*/\1/')
  if [ "${camera}" = "${QUERY_STRING}" ]; then camera='+'; fi
fi

if [ ! -z "${QUERY_STRING:-}" ]; then
  days=$(echo "$QUERY_STRING" | sed 's/.*days=\([^&]*\).*/\1/')
  if [ "${days}" = "${QUERY_STRING}" ]; then days=1; fi
fi

echo "Content-Type: application/json; charset=utf-8"
echo "Access-Control-Allow-Origin: *"
echo "Cache-Control: no-cache"
echo "Cache-Control: max-age=30"
echo ""
./bin/cleanup.sh ${camera} ${days}
