FROM %%BASE_IMAGE%%
#FROM homeassistant/amd64-base:latest

ENV LANG C.UTF-8
#LABEL io.hass.version="00"

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update

# REQUIRED: packages
RUN apk add mosquitto-clients jq

# Copy "ageathome" scripts 
COPY ../../../cgi/*.{csh,cgi,bash} /cgi
COPY ../../../bin/* /usr/local/bin

# copy start script
COPY run.sh /usr/local/bin

COPY ageathome.conf /etc/ageathome/ageathome.conf

# Ports for motion (control and stream)
EXPOSE 80

# Create volume to store images & videos
VOLUME ["/var/lib/age-at-home"]

# set working directory
WORKDIR /var/lib/age-at-home

# invoke motion detection script (NOT as daemon; re-direct logging to STDERR)
CMD [ "/usr/local/bin/run.sh" ]
