title: Horizon YOLO POC

views:
  - icon: mdi:radio
    id: YOLO
    cards:
      - type: history-graph
        title: Activity
        refresh_interval: 10
        hours_to_show: 1 
        entities:
          - entity: sensor.yolo2msghub_count
            icon: mdi:sigma
            name: Events
      - type: history-graph
        title: Sentiment
        refresh_interval: 10
        hours_to_show: 1 
        entities:
          - entity: sensor.yolo2msghub_sentiment_score
            icon: mdi:arrow-up-down-bold-outline
            name: Score
          - entity: sensor.yolo2msghub_sentiment_mean
            icon: mdi:heart-half-full
            name: Mean
      - type: map
        title: YOLO
        aspect_ratio: 100%
        default_zoom: 1
        entities:
          - sensor.yolo2msghub_event
          - zone.home
      - type: entities
        entities:
          - entity: sensor.yolo2msghub_event
            icon: mdi:emoticon-dead
            name: Live
          - entity: sensor.yolo2msghub_count
            icon: mdi:sigma
            name: Count
          - entity: sensor.yolo2msghub_ratio
            name: Ratio
            icon: mdi:percent
          - entity: sensor.yolo2msghub_date
            icon: mdi:clock-outline
            name: When
          - entity: sensor.yolo2msghub_name
            icon: mdi:account-outline
            name: Who
          - entity: sensor.yolo2msghub_bytes
            icon: mdi:memory
            name: Size
          - entity: sensor.yolo2msghub_frequency
            icon: mdi:access-point
            name: Frequency
          - entity: sensor.yolo2msghub_keywords
            icon: mdi:key
            name: Keywords
          - entity: sensor.yolo2msghub_sentiment_score
            icon: mdi:arrow-up-down-bold-outline
            name: Sentiment score
          - entity: sensor.yolo2msghub_sentiment_mean
            icon: mdi:heart-half-full
            name: Sentiment mean
          - entity: sensor.yolo2msghub_sentiment_label
            icon: mdi:plus-minus
            name: Sentiment label
          - entity: sensor.yolo2msghub_characters
            icon: mdi:sigma
            name: Text length
          - entity: sensor.yolo2msghub_language
            icon: mdi:translate
            name: Language
      - type: entities
        entities:
          - entity: input_number.yolo2msghub_relevance
            icon: mdi:tune
            name: Relevance
          - entity: sensor.yolo2msghub_relevance_minimum
            icon: mdi:greater-than-or-equal
            name: Relevance
#          - entity: input_number.yolo2msghub_confidence
#            icon: mdi:tune
#            name: Confidence
#          - entity: sensor.yolo2msghub_confidence_minimum
#            icon: mdi:greater-than-or-equal
#            name: Confidence
#          - entity: sensor.yolo2msghub_all_keywords
#            icon: mdi:key
#            name: All keywords
